name: 'ghostscript-setup-action'
description: 'Installs ghostscript for all OSes'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import sys, os, glob
        sys.path.insert(0, os.path.join(os.environ['GITHUB_ACTION_PATH'], '..', '_shared'))
        from tool_runner import get_platform_name, run_commands

        platform_name = get_platform_name()

        if platform_name == "Windows":
          run_commands([
            "choco install --no-progress -y ghostscript",
          ])
          gs_dirs = sorted(glob.glob("C:\\Program Files\\gs\\gs*"))
          if gs_dirs:
            gs_root = gs_dirs[-1]
            gs_bin = os.path.join(gs_root, "bin")
            gs_lib = os.path.join(gs_root, "lib")
            run_commands([
              "echo {}>> {}".format(gs_bin, os.environ["GITHUB_PATH"]),
              "echo {}>> {}".format(gs_lib, os.environ["GITHUB_PATH"]),
              "\"{}\\gswin64c.exe\" --version".format(gs_bin),
              "\"{}\\ps2pdf\" --version".format(gs_lib),
            ])
          else:
            print("Ghostscript installation directory not found")
            sys.exit(1)
        else:
          run_commands({
            "Darwin": [
              "brew install ghostscript",
              "gs --version",
            ],
            "Ubuntu": [
              "sudo apt install -y ghostscript",
              "which gs",
              "gs --version",
              "which ps2pdf",
            ],
            "Linux": [
              "sudo apt install -y ghostscript",
              "which gs",
              "gs --version",
              "which ps2pdf",
            ],
          }.get(platform_name, [
            "echo 'Unsupported platform: {}'".format(platform_name),
            "exit 1"
          ]))
