name: 'inkscape-setup-action'
description: 'composite action which installs inkscape for all OSes'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import os
        import sys
        import platform

        prefix = "{}\\inkscape\\bin\\".format(os.getcwd()) if platform.system() == "Windows" else ""

        cmds = {
          "Darwin": [ "brew install --cask inkscape" ],
          # commented because of https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1717
          # "Windows": [ "choco install --no-progress -y inkscape" ],
          "Windows": [
            "bitsadmin /transfer inkscapedwnld /download /priority FOREGROUND \"https://media.inkscape.org/dl/resources/file/inkscape-1.1-x64.7z\" \"{}\\inkscape.7z\"".format(os.getcwd()),
            "7z x \".\\inkscape.7z\" -y",
            "echo {}>> {}".format(prefix, os.environ["GITHUB_PATH"])
          ],
          "Linux": [
            "sudo add-apt-repository ppa:inkscape.dev/stable",
            "sudo apt update",
            "sudo apt install inkscape"
          ]
        }.get(platform.system(), [ "echo \"Unsupported platform: {}\"".format(platform.system()) ])

        cmds.append("{}inkscape --version".format(prefix))

        for cmd in cmds:
          if os.system(cmd) != 0:
            print("Command {} FAILED!".format(cmd))
            sys.exit(1)
