name: 'inkscape-setup-action'
description: 'composite action which installs inkscape for all OSes'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import os
        import sys
        import platform

        win_prefix = "C:\\Program Files\\Inkscape\\bin"

        cmds = {
          "Darwin": [ "brew install --cask inkscape", "inkscape --version" ],
          "Windows": [
            "choco install --no-progress -y inkscape",
            "echo {}>> {}".format(win_prefix, os.environ["GITHUB_PATH"]),
            "\"{}\\inkscape\" --version".format(win_prefix)
          ],
          "Linux": [
            "sudo add-apt-repository ppa:inkscape.dev/stable",
            "sudo apt update",
            "sudo apt install inkscape",
            "inkscape --version"
          ]
        }.get(platform.system(), [ "echo \"Unsupported platform: {}\"".format(platform.system()), "exit 1" ])

        for cmd in cmds:
          if os.system(cmd) != 0:
            print("Command {} FAILED!".format(cmd))
            sys.exit(1)
