name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/windows.yml

jobs:
  test-linux:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
        experimental: [false]
        include:
          - ruby: '2.7'
            experimental: true
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Install LaTeXML
        run: |
          sudo snap install latexml --edge
          echo "::add-path::/snap/bin"
      - name: Install PlantUML
        uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: sudo bash -c "curl -L https://github.com/metanorma/plantuml-install/raw/master/ubuntu.sh | bash"
      - name: Install puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1
          npm install -g puppeteer@3.0.1
      - name: Run specs
        run: |
          bundle exec rake
