name: docker

on:
  push:
    branches: [ master, main ]
  pull_request:
    paths-ignore:
      - .gitlab-ci.yml
      - .github/workflows/test.yml
      - .github/workflows/generate.yml
  repository_dispatch:
    types: [ metanorma/metanorma-docker ]
  workflow_dispatch:

jobs:
  test-docker:
    uses: metanorma/metanorma-build-scripts/workflows/sample-docker.yml@main
