name: docker-pres_xml

on:
  repository_dispatch:
    types: [ metanorma/metanorma-docker/feature/pres_xml ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn:pres_xml
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN || github.token }}
          submodules: true

      - run: curl -L --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/gemfile-to-bundle-add.sh | bash

      - run: metanorma site generate --agree-to-terms

      - uses: actions/upload-artifact@master
        if: github.ref == 'refs/heads/master'
        with:
          name: site
          path: site
