name: macos

on:
  push:
    branches: [ master, main ]
  pull_request:
    paths-ignore:
      - .gitlab-ci.yml
      - .github/workflows/test.yml
      - .github/workflows/docker.yml
      - .github/workflows/ubuntu.yml
      - .github/workflows/windows.yml
      - .github/workflows/docker-pres_xml.yml

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN || github.token }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.cache/xml2rfc
          key: xml2rfc
          restore-key: xml2rfc

      - run: brew install metanorma/metanorma/metanorma

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install relaton
        run: |
          gem install relaton-cli
      - name: Metanorma compile
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          metanorma site generate sources --output-dir site
