name: macos

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-macos:
    name: Test on Ruby ${{ matrix.ruby }} macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Cache xml2rfc
        id: cache-xml2rfc
        uses: actions/cache@v1
        with:
          path: ~/.cache/xml2rfc
          key: xml2rfc
          restore-key: xml2rfc
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Install bundler
        run: |
          sudo gem install bundler
      - name: Use Metanorma
        run: |
          brew update
          brew install yq
          brew unlink node@12
          brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
          metanorma version
      - name: Metanorma compile
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          export NODE_PATH=$(brew --prefix metanorma)/libexec/lib/node_modules
          source $(brew --prefix metanorma)/libexec/venv/bin/activate
          make clean all
