name: gems-test

on:
  repository_dispatch:
    types: [ metanorma/metanorma-* ]

jobs:
  test-docker:
    uses: mmetanorma/metanorma-build-scripts/.github/workflows/sample-test.yml@main
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
