name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-linux:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Cache xml2rfc
        id: cache-xml2rfc
        uses: actions/cache@v1
        with:
          path: ~/.cache/xml2rfc
          key: xml2rfc
          restore-key: xml2rfc
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Install bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Use Metanorma
        run: |
          curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | sudo bash
          sudo chown -R $USER:$(id -gn $USER) $HOME/.config
          metanorma version
      - name: Install yq
        run: |
          sudo snap install yq
      - name: Metanorma compile
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          source $HOME/.nvm/nvm.sh
          nvm use mn-node
          make clean all publish
