name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test-windows:
    name: Test on Ruby ${{ matrix.ruby }} Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        shell: pwsh
        run: |
          gem install bundler
          bundle update --bundler
          bundle install --jobs 4 --retry 3
      - name: Use Metanorma
        shell: pwsh
        run: |
          cinst -y metanorma
      - name: Install yq
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/mikefarah/yq/releases/download/2.4.0/yq_windows_amd64.exe " -OutFile ".\yq.exe"
      - name: Metanorma compile
        run: |
          make -f Makefile.win clean all SHELL=cmd
