name: windows

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-windows:
    name: Test on Ruby ${{ matrix.ruby }} Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Cache xml2rfc
        id: cache-xml2rfc
        uses: actions/cache@v1
        with:
          path: ~/.cache/xml2rfc
          key: xml2rfc
          restore-key: xml2rfc
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Install bundler
        run: |
          gem install bundler
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Use Metanorma
        shell: pwsh
        run: |
          cinst --no-progress -y metanorma
      - name: Install yq
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/mikefarah/yq/releases/download/2.4.0/yq_windows_amd64.exe " -OutFile ".\yq.exe"
      - name: Metanorma compile
        run: |
          make -f Makefile.win clean all SHELL=cmd
