name: debian

on:
  push:
    branches-ignore:
      # disabled to reduce CI usage for private repos
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian
    steps:
      # cabextract for fonts, gettext-base for envsubst, libxml2-utils for xmllint
      - name: Setup prerequisites
        run: |
          apt-get update
          apt-get -y install gettext-base cabextract wget libxml2-utils curl \
            software-properties-common gcc ruby ruby-dev libffi-dev libsass-dev make \
            libxml2-dev libxslt1-dev zlib1g-dev zlib1g pkg-config g++ default-jre gnupg \
            git
          apt-get -y install xmlstarlet

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          submodules: recursive

      - name: Install yq
        run: |
          GO111MODULE=on go get github.com/mikefarah/yq/v3
          ln -s $GOPATH/bin/yq /usr/local/bin/yq

      - name: Update gems
        run: |
          gem install bundler
          make Gemfile
          bundle config build.nokogiri --use-system-libraries
          bundle install --jobs 4 --retry 3

      - run: make all published
