name: 'graphviz-setup-action'
description: 'Installs graphviz for all OSes'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import sys, os
        sys.path.insert(0, os.path.join(os.environ['GITHUB_ACTION_PATH'], '..', '_shared'))
        from tool_runner import get_platform_name, run_commands

        platform_name = get_platform_name()
        run_commands({
          "Darwin": [
            "brew install graphviz",
            "dot -V"
          ],
          "Windows": [
            "choco install --no-progress -y graphviz",
            "dot -V"
          ],
          "Ubuntu": [
            "sudo apt update",
            "sudo apt install -y graphviz",
            "dot -V"
          ],
          "Linux": [
            "sudo apt update",
            "sudo apt install -y graphviz",
            "dot -V"
          ],
        }.get(platform_name, [
          "echo 'Unsupported platform: {}'".format(platform_name),
          "exit 1"
        ]))
