name: 'graphviz-setup-action'
description: 'composite action which installs graphviz for all OSes'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import os
        import sys
        import platform

        cmds = {
          "Darwin": [ "brew install graphviz" ],
          "Windows": [ "cinst --no-progress -y graphviz" ],
          "Linux": [
            "sudo apt update",
            "sudo apt install graphviz"
          ]
        }.get(platform.system(), [ "echo \"Unsupported platform: {}\"".format(platform.system()), "exit 1" ])

        cmds.append("dot -V")

        for cmd in cmds:
          if os.system(cmd) != 0:
            print("Command {} FAILED!".format(cmd))
            sys.exit(1)
