name: test

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    name: Run specs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - if: matrix.os == 'windows-latest'
        run: choco install --no-progress xsltproc wget sed

      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install xsltproc libxml2-utils

      - if: matrix.os == 'macos-latest'
        run: brew install libxml2

      - uses: actions/checkout@master

      - run: bash test.sh