name: update-repo

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * *

jobs:
  update-repo:
    name: Update repository
    runs-on: ubuntu-latest
    env:
      BRANCH: test # TODO replace with master
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - run: gem install stepmod-utils

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - run: |
          git config --global user.name "metanorma-ci"
          git config --global user.email "metanorma-ci@users.noreply.github.com"

      - run: |
          git remote add cvs https://github.com/metanorma/iso-10303-stepmod-cvs
          git fetch cvs

          git switch -c ${{ env.BRANCH }}
          git reset --hard cvs/master
          git remote remove cvs

          stepmod-annotate-all .
          git add -u
          git commit -m "Add stepmod annotations" || echo "Nothing to commit"

      - run: |
          mkdir -p .github/workflows
          wget https://raw.githubusercontent.com/metanorma/ci/master/cimas-config/gh-actions/iso-10303-stepmod/update-repo.yml -O .github/workflows/update-repo.yml
          git add .github/workflows/update-repo.yml
          git commit -m "Add GHA update-repo workflow"

      - run: git push origin ${{ env.BRANCH }} -f -vv
