name: update-repo

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * *

jobs:
  convert:
    name: Update repository
    runs-on: ubuntu-latest

    steps:
      - run: git init iso-10303-stepmod

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - run: gem install stepmod-utils

      - working-directory: ./iso-10303-stepmod
        run: |
          git config --global user.name "metanorma-ci"
          git config --global user.email "metanorma-ci@users.noreply.github.com"

          git remote add cvs https://metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}@github.com/metanorma/iso-10303-stepmod-cvs
          git pull cvs master --ff-only --depth 1

          git switch -c test
          git merge cvs/master
          git remote remove cvs

          stepmod-annotate-all .

      - working-directory: ./iso-10303-stepmod
        run: |
          mkdir -p .github/workflows
          wget https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/cimas-config/gh-actions/iso-10303-stepmod/update-repo.yml -O .github/workflows/update-repo.yml
          git add .github/workflows/update-repo.yml
          git commit -m "Add GHA update-repo workflow"

      - working-directory: ./iso-10303-stepmod
        run: |
          git remote add origin https://github.com/metanorma/iso-10303-stepmod
          git push origin test -f
