name: update-repo

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * *

jobs:
  convert:
    name: Update repository
    runs-on: ubuntu-latest

    steps:
      - run: git init iso-10303-stepmod

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - run: gem install stepmod-utils

      - working-directory: ./iso-10303-stepmod
        run:
          git config user.name github-actions
          git config user.email github-actions@github.com

          git remote add cvs https://github.com/metanorma/iso-10303-stepmod-cvs
          git fetch cvs --no-checkout --depth 1
          git checkout master cvs/master
          git remote remove cvs

          stepmod-annotate-all .

      - working-directory: ./iso-10303-stepmod
        run:
          mkdir -p .github/workflow
          wget https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/cimas-config/gh-actions/iso-10303-stepmod/update-repo.yml -O .github/workflow/update-repo.yml
          git add .github/workflow/update-repo.yml
          git commit -m "Add GHA update-repo workflow"

      - working-directory: ./iso-10303-stepmod
        run:
          git remote add origin https://github.com/metanorma/iso-10303-stepmod
          echo "TODO git push origin master -f"
