name: release-github-packages

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch (or pre|rc|etc).
          Also, you can pass 'skip' to skip 'git tag' and do 'gem push' for the current version
        required: true
        default: 'skip'
  repository_dispatch:
    types: [ do-release ]

jobs:
  release:
    uses: metanorma/ci/.github/workflows/ghpkg-release.yml@main
    with:
      next_version: ${{ github.event.inputs.next_version }}
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}