name: release-github-packages

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'
  push:
    tags: [ v* ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - run: gem install gem-release

      - if: ${{ github.event_name == 'workflow_dispatch' }} && ${{ github.event.inputs.next_version != 'skip' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          gem bump --version ${{ github.event.inputs.next_version }} --tag --push

      - name: publish to GitHub Packages
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        run: |
          envsubst << 'EOF' > ~/.gem/credentials
          ---
          :github: Bearer ${GITHUB_PACKAGES_TOKEN}
          EOF
          chmod 0600 ~/.gem/credentials
          gem release --key github --host https://rubygems.pkg.github.com/metanorma

