name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:

jobs:
  rake:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
        include:
          - ruby: '2.7'
            os: 'ubuntu-latest'
            experimental: true
          - ruby: '2.7'
            os: 'windows-latest'
            experimental: true
          - ruby: '2.7'
            os: 'macos-latest'
            experimental: true
    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: bundle-${{ matrix.os }}-${{ matrix.ruby }}

      - run: bundle config set path 'vendor/bundle'

      - run: bundle install --jobs 4 --retry 3

      - name: install libre-office windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install libreoffice-still
          echo "::add-path::C:\Program Files\LibreOffice\program"

      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get -y --no-install-recommends install libreoffice

      - run: bundle exec rake
