name: 'gh-packages-setup-action'
description: 'composite action which setup metanorma private GitHub packages for rubygems'
inputs:
  username:
    description: 'GitHub username'
    required: true
    default: metanorma-ci
  token:
    description: 'personal access token (PAT)'
    required: true
  owner:
    description: 'the name of the user or organization account that owns the repository containing your project.'
    required: true
    default: metanorma
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cat << 'EOF' > ~/.gemrc
        ---
        :backtrace: false
        :bulk_threshold: 1000
        :sources:
        - https://${{ inputs.username }}:${{ inputs.token }}@rubygems.pkg.github.com/${{ inputs.owner }}/
        - https://rubygems.org/
        :update_sources: true
        :verbose: true
        EOF
        echo "~/.gemrc generated!"

    - shell: bash
      run: |
        bundle config https://rubygems.pkg.github.com/${{ inputs.owner }} ${{ inputs.username }}:${{ inputs.token }}
        echo "https://rubygems.pkg.github.com/${{ inputs.owner }} added to bundler's config"