name: 'gh-packages-setup-action'
description: 'composite action which setup metanorma private GitHub packages for rubygems'
inputs:
  token:
    description: 'personal access token (PAT)'
    required: true
  owner:
    description: 'the name of the user or organization account that owns the repository containing your project.'
    required: true
    default: metanorma
  local:
    description: 'true if local config need to be modified, false by default'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: source ${GITHUB_ACTION_PATH//\\//}/gen-gemrc-for-gh-packages.sh ${{ inputs.token }} ${{ inputs.owner }}
      shell: bash

    - run: source ${GITHUB_ACTION_PATH//\\//}/gen-bundle-config-for-gh-packages.sh ${{ inputs.token }} ${{ inputs.owner }} ${{ inputs.local && '--local' || '--global' }}
      shell: bash

    - run: |
        cat ~/.gemrc
        cat ~/.bundle/config
      shell: bash