name: 'gh-packages-setup-action'
description: 'composite action which setup metanorma private GitHub packages for rubygems'
inputs:
  token:
    description: 'personal access token (PAT)'
    required: true
  owner:
    description: 'the name of the user or organization account that owns the repository containing your project.'
    required: true
    default: metanorma
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ -f "~/.gemrc" ]; then
          echo "WARNING! Overwriting ~/.gemrc."
        fi
        cat << 'EOF' > ~/.gemrc
        ---
        :backtrace: false
        :bulk_threshold: 1000
        :sources:
        - https://x-access-token:${{ inputs.token }}@rubygems.pkg.github.com/${{ inputs.owner }}/
        - https://rubygems.org/
        :update_sources: true
        :verbose: true
        EOF
        echo "~/.gemrc generated!"

    - shell: bash
      run: |
        if command -v bundle &> /dev/null; then
          bundle config https://rubygems.pkg.github.com/${{ inputs.owner }} x-access-token:${{ inputs.token }}
          echo "https://rubygems.pkg.github.com/${{ inputs.owner }} added to bundler's config"
        else
          echo "bundler not installed. so defining BUNDLE_RUBYGEMS__PKG__GITHUB__COM ..."
          echo "BUNDLE_RUBYGEMS__PKG__GITHUB__COM=x-access-token:${{ inputs.token }}" >> $GITHUB_ENV

          echo "generating ~/.bundle/config ..."
          if [ -f "~/.bundle/config" ]
          then
            echo "WARNING! Overwriting ~/.bundle/config"
          fi
          mkdir -p ~/.bundle
          OWNER_UPPER=$(echo "${{ inputs.owner }}" | tr '[:lower:]' '[:upper:]')
          cat > ~/.bundle/config << 'EOF'
          ---
          BUNDLE_HTTPS://RUBYGEMS__PKG__GITHUB__COM/$OWNER_UPPER/: "x-access-token:${{ inputs.token }}"
          EOF
        fi
