language: ruby
cache: bundler
os:
- linux
- osx
rvm:
- 2.6
- 2.5
- 2.4
- 2.3
- ruby-head
before_install: 
- gem update --system
- gem install bundler -v "~> 2"
- bundle update
matrix:
  allow_failures:
    - rvm: ruby-head