language: ruby
cache: bundler
os:
- linux
- osx
rvm:
- 2.6
- 2.5
- 2.4
- ruby-head
before_install: 
- nvm install 8
- npm install -g puppeteer
- npm install
- gem install bundler -v "~> 2"
- bundle update
- curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/travis.sh | bash
matrix:
  allow_failures:
    - rvm: ruby-head

