name: 'libreoffice-setup-action'
description: 'Installs libreoffice for Windows and Linux'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import sys, os
        sys.path.insert(0, os.path.join(os.environ['GITHUB_ACTION_PATH'], '..', '_shared'))
        from tool_runner import get_platform_name, run_commands

        platform_name = get_platform_name()
        run_commands({
          "Darwin": [],
          "Windows": [
            "choco install --no-progress -y libreoffice-still",
            "echo C:\\Program Files\\LibreOffice\\program>> %GITHUB_PATH%",
            "\"C:\\Program Files\\LibreOffice\\program\\soffice\" --version",
          ],
          "Ubuntu": [
            "sudo apt-get update",
            "sudo apt-get -y --no-install-recommends install libreoffice",
            "soffice --version",
          ],
          "Linux": [
            "sudo apt-get update",
            "sudo apt-get -y --no-install-recommends install libreoffice",
            "soffice --version",
          ],
        }.get(platform_name, [
          "echo 'Unsupported platform: {}'".format(platform_name),
          "exit 1"
        ]))
