name: 'libreoffice-setup-action'
description: 'composite action which installs libreoffice for Windows and Linux'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import os
        import platform

        win_prefix = "C:\\Program Files\\LibreOffice\\program\\"

        cmds = {
          "Darwin": [ ],
          "Windows": [
            "choco install --no-progress -y libreoffice-still",
            "echo {}>> {}".format(win_prefix, os.environ["GITHUB_PATH"]),
            "\"{}soffice\" --version".format(win_prefix)
          ],
          "Linux": [
            "sudo apt-get -y --no-install-recommends install libreoffice",
            "soffice --version"
          ]
        }.get(platform.system(), [ "echo \"Unsupported platform: {}\"".format(platform.system()), "exit 1" ])

        for cmd in cmds:
          if os.system(cmd) != 0:
            print("Command {} FAILED!".format(cmd))
            sys.exit(1)
