name: 'libreoffice-setup-action'
description: 'composite action which installs libreoffice for Windows and Linux'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import os
        import platform

        cmds = {
          "Darwin": [ ],
          "Windows": [
            "cinst --no-progress -y libreoffice-still",
            "echo C:\\Program Files\\LibreOffice\\program>> {}".format(os.environ["GITHUB_PATH"])
          ],
          "Linux": [
            "sudo apt-get -y --no-install-recommends install libreoffice"
          ]
        }.get(platform.system(), [ "echo \"Unsupported platform: {}\"".format(platform.system()) ])

        if cmds:
          cmds.append("soffice --version")

        [os.system(cmd) for cmd in cmds]
