name: 'fontist-setup-action'
description: 'composite action which setup metanorma private GitHub packages for rubygems'
inputs:
  force-install:
    description: 'Force install if already installed'
    required: false
    default: ''
  private-fonts-pat:
    description: 'Setup private formulas with PAT'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
  - id: check
    run: |
      if command -v fontist &> /dev/null
      then
        echo "fontist-installed=true" >> $GITHUB_OUTPUT
      else
        echo "fontist-installed=false" >> $GITHUB_OUTPUT
      fi

      if command -v ruby &> /dev/null
      then
        echo "ruby-installed=true" >> $GITHUB_OUTPUT
      else
        echo "ruby-installed=false" >> $GITHUB_OUTPUT
      fi
    shell: bash

  - if: ${{ steps.check.outputs.ruby-installed == 'false' }}
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: '3.3'

  - if: ${{ steps.check.outputs.fontist-installed == 'false' || inputs.force-install == 'true' }}
    run: |
      if gem install fontist; then
        echo "Fontist installed successfully"
      elif [[ "${{ runner.os }}" != "Windows" ]]; then
        sudo gem install fontist
      else
        echo "Failed to install fontist" && exit 1
      fi
    shell: bash

  - if: ${{ inputs.private-fonts-pat != '' }}
    run: |
      fontist update
      fontist repo setup metanorma https://metanorma-ci:${{ inputs.private-fonts-pat }}@github.com/metanorma/fontist-formulas-private
      fontist repo update metanorma
    shell: bash
