name: 'fontist-setup-action'
description: 'composite action which setup metanorma private GitHub packages for rubygems'
inputs:
  force-install:
    description: 'Force install if already installed'
    required: false
    default: ''
  private-fonts-pat:
    description: 'Setup private formulas with PAT'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
  - id: check
    run: |
      if command -v fontist &> /dev/null
      then
        echo "fontist-installed=true" >> $GITHUB_OUTPUT
      else
        echo "fontist-installed=false" >> $GITHUB_OUTPUT
      fi

      if command -v ruby &> /dev/null
      then
        echo "ruby-installed=true" >> $GITHUB_OUTPUT
      else
        echo "ruby-installed=false" >> $GITHUB_OUTPUT
      fi
    shell: bash

  - if: ${{ steps.check.outputs.ruby-installed == 'false' }}
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: '3.0'

  - if: ${{ steps.check.outputs.fontist-installed == 'false' || inputs.force-install == 'true' }}
    run: |
      import os
      import platform
      rc = os.system("gem install fontist")
      if rc != 0 and platform.system() != "Windows":
        os.system("sudo gem install fontist")
    shell: python

  - if: ${{ inputs.private-fonts-pat != '' }}
    run: |
      import os
      os.system("fontist update")
      os.system("fontist repo setup metanorma https://metanorma-ci:${{ inputs.private-fonts-pat }}@github.com/metanorma/fontist-formulas-private")
      os.system("fontist repo update metanorma")
    shell: python
