name: choco-cache-action
description: This action cache chocolatey cache location
inputs:
  cache-path:
    description: path to store chocolatey cache
    default: 'vendor\choco'

runs:
  using: "composite"
  steps:
  - shell: pwsh
    run: |
      $cachePath = "${{ inputs.cache-path }}"
      if (-not [System.IO.Path]::IsPathRooted($cachePath)) {
          $cachePath = Join-Path -Path (Get-Location).Path -ChildPath $cachePath
      }
      New-Item -Path $cachePath -ItemType Directory -Force

      choco config get cacheLocation
      choco config set cacheLocation "$cachePath"
      choco config get cacheLocation

  - uses: actions/cache@v4
    with:
      path: ${{ inputs.cache-path }}
      key: chocolatey-cache
      restore-keys: chocolatey-cache
