name: choco-action-action
description: This action cache chocolatey cache location
inputs:
  cache-path:
    description: path to store chocolatey cache
    default: 'vendor/choco'

runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      choco config get cacheLocation
      choco config set cacheLocation ${{ inputs.cache-path }}

  - uses: actions/cache@v4
    with:
      path: ${{ inputs.cache-path }}
      key: chocolatey-cache
      restore-keys: chocolatey-cache
