name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/windows.yml

jobs:
  test-linux:
    name: Test on PlantUML Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install PlantUML
        run: |
          sudo bash -c "curl -L https://github.com/riboseinc/plantuml-install/raw/master/ubuntu.sh | bash"
      - name: Make
        run: |
          make clean all

