name: 'plantuml-setup-action'
description: 'composite action which installs plantuml for all OSes'
runs:
  using: "composite"
  steps:
    - shell: python
      run: |
        import os
        import sys
        import platform

        cmds = {
          "Darwin": [ "brew install plantuml" ],
          "Windows": [ "choco install -y --no-progress plantuml" ],
          "Linux": [
            "sudo apt update",
            "sudo apt install plantuml"
          ]
        }.get(platform.system(), [ "echo \"Unsupported platform: {}\"".format(platform.system()) ])

        cmds.append("plantuml -version")

        for cmd in cmds:
          if os.system(cmd) != 0:
            print("Command {} FAILED!".format(cmd))
            sys.exit(1)
