name: docker

on:
  push:
    branches: [ master, main  ]
  pull_request:
    paths-ignore:
      - .github/workflows/test.yml
  repository_dispatch:
    types: [ metanorma/metanorma-docker ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN || github.token }}
          submodules: true

      - name: Metanorma compile
        shell: bash
        run: |
          source doctypes.env
          for template in $DOCTYPES
          do
            metanorma new test/$template --type $TYPE --doctype $template --template . --overwrite
            if [ -f test/${template}/document.adoc ]
            then
              metanorma compile test/${template}/document.adoc
            else
              for docfile in test/${template}/*.adoc
              do
                metanorma compile $docfile
              done
            fi
          done