name: test

on:
  push:
    branches: [ master, main  ]
  pull_request:
  repository_dispatch:
    types: [ metanorma/metanorma-cli ]

jobs:
  test:
    name: Test ruby-${{ matrix.ruby }} on ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        ruby: [ '2.6', '2.5', '2.4' ]
        experimental: [ false ]
        include:
          - ruby: '2.7'
            os: macos-latest
            experimental: true
          - ruby: '2.7'
            os: ubuntu-latest
            experimental: true
          - ruby: '2.7'
            os: windows-latest
            experimental: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - if: matrix.os == 'macos-latest'
        run: brew install autoconf automake libtool

      - name: Install metanorma
        shell: python
        env:
          TRIGGER_REPO: ${{ github.event.client_payload.repo }}
          TRIGGER_REF: ${{ github.event.client_payload.ref }}
        run: |
          import os

          repo = os.environ.get("TRIGGER_REPO")
          branch = os.environ.get("TRIGGER_REF")

          print("Install {} {}".format(repo, branch))

          if repo != "metanorma/metanorma-cli":
            os.system("gem install metanorma-cli")

          if branch and repo:
            os.system("gem install specific_install")
            os.system("gem specific_install -l https://github.com/{}.git -b {}".format(repo, branch))

      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'

      - run: pip install xml2rfc

      - name: Metanorma compile *nix
        if: matrix.os != 'windows-latest'
        run: |
          source doctypes.env
          for template in $DOCTYPES
          do
            metanorma new test/$template --type $TYPE --doctype $template --template . --overwrite
            if [ -f test/${template}/document.adoc ]
            then
              metanorma compile test/${template}/document.adoc
            else
              for docfile in test/${template}/*.adoc
              do
                metanorma compile $docfile
              done
            fi
          done

      - name: Metanorma compile Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop" <# https://stackoverflow.com/a/16334189/902217 #>
          $docTypes = ConvertFrom-StringData (Get-Content ./doctypes.env -Raw)
          $docTypes.DOCTYPES.Split(" ") | % {
            $t = $_.Trim('"')
            metanorma new result\$t --type $($docTypes.TYPE) --doctype $t --template . --overwrite
            $doc = "result\$t\document.adoc"
            if (Test-Path -Path $doc) {
              metanorma compile $doc
            } else {
              Get-ChildItem ".\result\$t" -Filter *.adoc | % {
                metanorma compile $_.FullName
              }
            }
          }
