name: release

on:
  workflow_call:
    inputs:
      next_version:
        required: true
        type: string
      event_name:
        description: 'deprecated github.event_name used instead'
        required: false
        type: string
      bundler_cache:
        description: 'do bundle install'
        required: false
        type: boolean
        default: true
      post_install:
        description: 'comamnd to execute after bundle install'
        required: false
        type: string
        default: ''
    secrets:
      pat_token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git fetch --tags origin

      - uses: metanorma/ci/gh-rubygems-setup-action@main
        with:
          token: ${{ secrets.pat_token }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: ${{ inputs.bundler_cache }}

      - if: ${{ inputs.post_install != '' }}
        run: ${{ inputs.post_install }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - if: github.event_name == 'workflow_dispatch' && inputs.next_version != 'skip'
        run: |
          gem install gem-release
          gem bump --version ${{ inputs.next_version }} --tag --push

      - name: publish to GitHub Packages
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.pat_token }}
        run: |
          envsubst << 'EOF' > ~/.gem/credentials
          ---
          :github: Bearer ${GITHUB_PACKAGES_TOKEN}
          EOF
          chmod 0600 ~/.gem/credentials
          bundle exec rake build
          # gem release - don't allow to execute rake tasks
          # rake release - finished with ERROR: too many connection resets
          gem push --key github --host https://rubygems.pkg.github.com/metanorma pkg/*.gem
