name: rake

on:
  workflow_call:
    secrets:
      pat_token:
        required: false

jobs:
  rake:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.ruby }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        ruby: [ '3.1', '3.0', '2.7' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
        include:
          - ruby: head
            os: ubuntu-latest
            experimental: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - if: matrix.ruby == '3.0'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest

      - if: matrix.ruby != '3.0'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: metanorma/metanorma-build-scripts/graphviz-setup-action@main

      - run: bundle exec rake

  tests-passed:
    needs: rake
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.pat_token || github.token }}
          repository: ${{ github.repository }}
          event-type: tests-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
