name: rake

on:
  workflow_call:
    secrets:
      pat_token:
        required: false

jobs:
  rake:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.ruby }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        ruby: [ '3.1', '2.7' ]
        os: [ ubuntu-latest, macos-latest ]
        experimental: [ false ]
        rubygems: [ default ]
        include:
          # https://github.com/rubygems/rubygems/issues/5970
          - ruby: '2.7'
            os: 'windows-latest'
            experimental: false
            rubygems: '3.3.22'
          - ruby: '3.0'
            os: 'windows-latest'
            experimental: false
            rubygems: '3.3.22'
          - ruby: '3.1'
            os: 'windows-latest'
            experimental: false
            rubygems: '3.3.22'
          # https://github.com/metanorma/metanorma-standoc/issues/620
          - ruby: '3.0'
            os: ubuntu-latest
            experimental: false
            rubygems: latest
          - ruby: '3.0'
            os: macos-latest
            experimental: false
            rubygems: latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: ${{ matrix.rubygems }}

      - uses: metanorma/ci/graphviz-setup-action@main

      - run: bundle exec rake

  tests-passed:
    needs: rake
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.pat_token || github.token }}
          repository: ${{ github.repository }}
          event-type: tests-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
