name: notify

on:
  workflow_call:
    secrets:
      pat_token:
        required: true
jobs:
  notify:
    name: Notify dependent repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - if: github.event.client_payload.type == 'tests-passed'
        name: Trigger test repositories
        env:
          GH_USERNAME: metanorma-ci
          GH_ACCESS_TOKEN: ${{ secrets.pat_token }}
        run: |
          curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/ci/master/trigger-gh-actions.sh
          [[ -f ".github/workflows/dependent_repos.env" ]] && source .github/workflows/dependent_repos.env
          CLIENT_PAYLOAD=$(cat <<EOF
          "{ "ref": "${{ github.event.client_payload.sha }}", "repo": "${GITHUB_REPOSITORY}" }"
          EOF
          )
          for repo in $TEMPLATE_REPOS" $SAMPLES_REPOS"
          do
            sh trigger-gh-actions.sh $ORGANISATION $repo $GH_USERNAME $GH_ACCESS_TOKEN $GITHUB_REPOSITORY "$CLIENT_PAYLOAD"
          done

      - name: Trigger release repositories
        if: github.event.client_payload.type == 'release-passed'
        env:
          GH_USERNAME: metanorma-ci
          GH_ACCESS_TOKEN: ${{ secrets.pat_token }}
        run: |
          curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/ci/master/trigger-gh-actions.sh
          [[ -f ".github/workflows/dependent_repos.env" ]] && source .github/workflows/dependent_repos.env
          CLIENT_PAYLOAD=$(cat <<EOF
          "{ "ref": "${{ github.event.client_payload.ref }}", "repo": "${GITHUB_REPOSITORY}" }"
          EOF
          )
          for repo in $DEPENDENT_REPOS
          do
            sh trigger-gh-actions.sh $ORGANISATION $repo $GH_USERNAME $GH_ACCESS_TOKEN $GITHUB_REPOSITORY "$CLIENT_PAYLOAD"
          done
