name: prepare-rake

on:
  workflow_call:
    outputs:
      head-tag:
        description: "Will be empty if there is not tag on HEAD"
        value: ${{ jobs.prepare.outputs.head_tag }}
      foreign-pr:
        description: "Return yes if this is a foreign PR"
        value: ${{ jobs.prepare.outputs.foreign_pr }}
      push-for-tag:
        description: "Return true if duplicatet run on tag exists and this can be skipped"
        value: ${{ jobs.prepare.outputs.push_for_tag }}
      matrix:
        description: "JSON string to be used in job.strategy.matrix"
        value: ${{ jobs.prepare.outputs.matrix }}
      default-ruby-version:
        description: "Default ruby version used for release or scripts"
        value: ${{ jobs.prepare.outputs.default_ruby_version }}

jobs:
  # https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
  prepare:
    runs-on: ubuntu-latest
    outputs:
      head_tag: ${{ steps.check.outputs.head_tag }}
      foreign_pr: ${{ steps.check.outputs.foreign_pr }}
      matrix: ${{ steps.matrix.outputs.value }}
      push_for_tag: ${{ steps.push_for_tag.outputs.value }}
      default_ruby_version: ${{ steps.config.outputs.default_ruby_version }}
    steps:
      - uses: actions/checkout@v3
      - name: retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
      - name: set output variables
        id: check
        run: |
          fpr="no"
          tag=""
          if [[ "${{ github.ref }}" == refs/heads/* ]]; then
            tag="$(git tag --points-at HEAD)"
          elif [[ "${{ github.ref }}" == refs/pull/* ]] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.event.pull_request.base.repo.full_name }}" ]; then
            fpr="yes"
          fi
          echo "foreign_pr=${fpr}" >> $GITHUB_OUTPUT
          echo "head_tag=${tag}" >> $GITHUB_OUTPUT

      - id: push_for_tag
        run: |
          value="${{ !(github.event_name == 'push' && steps.check.outputs.head_tag == '') && github.event_name != 'pull_request' }}"
          echo "value=${value}"
          echo "value=${value}" >> $GITHUB_OUTPUT

      - id: matrix
        run: |
          value="$(curl -L -k https://raw.githubusercontent.com/metanorma/ci/main/.github/workflows/ruby-matrix.json)"
          echo "value=$(echo ${value} | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - id: config
        run: |
          value="$(curl -L -k https://raw.githubusercontent.com/metanorma/ci/main/.github/workflows/config.json | jq .ruby.version -r)"
          echo "default_ruby_version=${value}" >> $GITHUB_OUTPUT
