name: docker-private

on:
  workflow_call:
    inputs:
      docker-image:
        default: 'metanorma/metanorma:latest'
        required: false
        type: string
      private-fonts:
        default: 'false'
        required: false
        type: string
      deploy-gh-pages:
        default: 'false'
        required: false
        type: string
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
      pat_username:
        required: false
      pat_token:
        required: false

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker-image }}
      credentials:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.pat_token || github.token }}
          submodules: true

      - if: ${{ inputs.private-fonts == 'true' }}
        run: |
          fontist update
          fontist repo setup metanorma https://metanorma-ci:${{ secrets.pat_token }}@github.com/metanorma/fontist-formulas-private
          fontist repo update metanorma

      - uses: metanorma/ci/gh-rubygems-setup-action@main
        with:
          token: ${{ secrets.pat_token }}

      - uses: metanorma/ci/docker-gem-install@main

      - uses: actions-mn/build-and-publish@main
        with:
          agree-to-terms: true
