name: generate

on:
  workflow_call:
    inputs:
      private-fonts:
        default: 'false'
        required: false
        type: string
    secrets:
      pat_token:
        required: false

jobs:
  site-generate:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.pat_token || github.token }}
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ~/.cache/xml2rfc
          key: xml2rfc
          restore-keys: xml2rfc

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - if: ${{ inputs.private-fonts == 'true' }}
        run: |
          gem install fontist
          fontist update
          fontist repo setup metanorma https://metanorma-ci:${{ secrets.pat_token }}@github.com/metanorma/fontist-formulas-private
          fontist repo update metanorma

      - uses: actions/cache@v3
        with:
          path: ~/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}

      - uses: actions/cache@v3
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - run: rm Gemfile

      - uses: actions-mn/setup@main

      - uses: actions-mn/site-gen@v1
        with:
          agree-to-terms: true
