name: gems-test

on:
  workflow_call:
    inputs:
      private-fonts:
        default: 'false'
        required: false
        type: string
    secrets:
      pat_token:
        required: false

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.ruby }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        ruby: [ '2.7', '3.0', '3.1' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.pat_token || github.token }}
          submodules: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - if: ${{ inputs.private-fonts == 'true' }}
        run: |
          bundle exec fontist update
          bundle exec fontist repo setup metanorma https://metanorma-ci:${{ secrets.pat_token }}@github.com/metanorma/fontist-formulas-private
          bundle exec fontist repo update metanorma

      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      - run: pip install xml2rfc

      - name: install metanorma
        shell: python
        env:
          TRIGGER_REPO: ${{ github.event.client_payload.repo }}
          TRIGGER_REF: ${{ github.event.client_payload.ref }}
        # TODO convert to composite action
        run: |
          import os

          repo = os.environ.get("TRIGGER_REPO")
          branch = os.environ.get("TRIGGER_REF")

          print("Install {} {}".format(repo, branch))

          if repo != "metanorma/metanorma-cli":
            os.system("gem install metanorma-cli")

          os.system("gem install specific_install")
          os.system("gem specific_install -l https://github.com/{}.git -b {}".format(repo, branch))

      - uses: actions-mn/cli/site-gen@main
        with:
          agree-to-terms: true

      - if: hashFiles('collection.yml') != ''
        uses: actions-mn/cli/collection@main
        with:
          manifest: collection.yml
          formats: xml,html,presentation,pdf
          cover-page: sources/collection_cover.html
          output-dir: collection
          agree-to-terms: true