name: generate

on:
  workflow_call:
    inputs:
      private-fonts:
        default: 'false'
        required: false
        type: string
    secrets:
      pat_token:
        required: false

jobs:
  site-generate:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.pat_token || github.token }}
          submodules: true

      - uses: actions-mn/setup@main

      - if: ${{ inputs.private-fonts == 'true' }}
        uses: metanorma/ci/fontist-setup@main
        with:
          private-fonts-pat: ${{ secrets.pat_token }}

      - run: rm Gemfile

      - uses: actions-mn/build-and-publish@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          agree-to-terms: true
          destination: artifact
          artifact-name: site-${{ matrix.os }}
