name: generate

on:
  workflow_call:
    secrets:
      pat_token:
        required: false

jobs:
  site-generate:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.pat_token || github.token }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.cache/xml2rfc
          key: xml2rfc
          restore-keys: xml2rfc

      - uses: actions/cache@v2
        with:
          path: ~/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}

      - uses: actions/cache@v2
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - if: matrix.os == 'windows-latest'
        run: rm Gemfile

      - uses: actions-mn/setup@master

      - uses: actions-mn/cli/site-gen@main
        with:
          agree-to-terms: true
