name: generate

on:
  workflow_call:
    secrets:
      pat_token:
        required: false

jobs:
  site-generate:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.pat_token || github.token }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.cache/xml2rfc
          key: xml2rfc
          restore-keys: xml2rfc

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - if: github.repository == 'metanorma/mn-samples-bsi'
        run: |
          gem install fontist
          fontist update
          fontist repo setup metanorma https://metanorma-ci:${{ secrets.pat_token }}@github.com/metanorma/fontist-formulas-private
          fontist repo update metanorma

      - uses: actions/cache@v2
        with:
          path: ~/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}

      - uses: actions/cache@v2
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - if: matrix.os == 'windows-latest'
        run: rm Gemfile

      - uses: actions-mn/setup@master

      - uses: actions-mn/cli/site-gen@main
        with:
          agree-to-terms: true

      - if: hashFiles('collection.yml') != ''
        uses: actions-mn/cli/collection@main
        with:
          manifest: collection.yml
          formats: xml,html,presentation,pdf
          cover-page: sources/collection_cover.html
          output-dir: collection
          agree-to-terms: true