name: pages

on:
  workflow_call:
    inputs:
      deploy-gh-pages:
        default: 'true'
        required: false
        type: string
    secrets:
      pat_token:
        required: true

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  generate-site:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.pat_token || github.token }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: /config/fonts
          key: fontist-docker
          restore-keys: fontist-docker

      - uses: actions/cache@v2
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - uses: metanorma/ci/gh-rubygems-setup-action@main
        with:
          token: ${{ secrets.pat_token }}

      - uses: metanorma/ci/docker-gem-install@main

      - uses: actions-mn/cli/site-gen@main
        with:
          agree-to-terms: true

      - uses: actions/upload-artifact@master
        with:
          name: site
          path: site

  deploy-gh-pages:
    if: ${{ inputs.deploy-gh-pages == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    needs: generate-site
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v1
        with:
          name: site

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./site
          force_orphan: true
          user_name: ${{ github.actor }}
          user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
          commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"

      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 0
