name: test-composite

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  test-scripts:
    name: Test scripts
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - run: ./gemver-to-semver.rb --self-test
  test-composite:
    name: Test composite actions ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v3

      - uses: ./graphviz-setup-action
      - run: dot -V

      - uses: ./inkscape-setup-action
      - run: inkscape --version

      - uses: ./libreoffice-setup-action
      - if: matrix.os != 'macos-latest'
        run: soffice --version

      - uses: ./plantuml-setup-action
      - run: plantuml -version

  test-gh-rubygem-setup-action-docker:
    name: Test gh-rubygems-setup-action & docker-gem-install in docker
    runs-on: ubuntu-latest
    container: docker://metanorma/metanorma
    steps:
      - uses: actions/checkout@v3

      - uses: ./gh-rubygems-setup-action
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - run: |
          echo 'gem "metanorma-cli"' > Gemfile
          echo 'gem "metanorma", "~>1"' >> Gemfile
          echo 'gem "metanorma-nist", source: "https://rubygems.pkg.github.com/metanorma"' >> Gemfile
          echo 'gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"' >> Gemfile

      - uses: ./docker-gem-install

  test-gh-rubygem-setup-action:
    name: Test gh-rubygems-setup-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - uses: ./gh-rubygems-setup-action
        with:
          token: dummy_token

      - run: |
          echo "cat ~/.gemrc"
          cat ~/.gemrc
          echo "cat ~/.bundle/config"
          cat ~/.bundle/config

      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.30.4

      - run: |
          yq -e e '.["BUNDLE_HTTPS://RUBYGEMS__PKG__GITHUB__COM/METANORMA/"] == "x-access-token:dummy_token"' ~/.bundle/config
          yq -e e '.[":sources"] | length == 2' ~/.gemrc

      - run: |
          env
          [ ${BUNDLE_GITHUB__COM} = "x-access-token:dummy_token" ] || exit 1
          [ ${BUNDLE_RUBYGEMS__PKG__GITHUB__COM} = "x-access-token:dummy_token" ] || exit 1
