name: test-composite

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  test-scripts:
    name: Test scripts
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - run: ./gemver-to-semver.rb --self-test
  test-composite:
    name: Test composite actions ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v2

      - uses: ./graphviz-setup-action
      - run: dot -V

      - uses: ./inkscape-setup-action
      - run: inkscape --version

      - uses: ./libreoffice-setup-action
      - if: matrix.os != 'macos-latest'
        run: soffice --version

      - uses: ./plantuml-setup-action
      - run: plantuml -version

  test-composite-docker:
    name: Test composite action for gem install workaround on docker
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@v2

      - uses: ./gh-rubygems-setup-action
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - run: |
          echo 'gem "metanorma-cli"' > Gemfile
          echo 'gem "metanorma", "~>1"' >> Gemfile
          echo 'gem "metanorma-nist", source: "https://rubygems.pkg.github.com/metanorma"' >> Gemfile
          echo 'gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"' >> Gemfile

      - uses: ./docker-gem-install
