name: generate

on:
  workflow_call:
    inputs:
      deploy:
        default: true
        required: false
        type: boolean

permissions:
  pull-requests: write
  contents: read
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Metanorma assets
        uses: actions-mn/cache@v1

      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@v1
        with:
          agree-to-terms: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions-mn/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
